/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Marvin Joel
 */
public class JIntFrmModificarProductoOferta extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntFrmModificarProductoOferta
     */
    public JIntFrmModificarProductoOferta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblCodigo = new javax.swing.JLabel();
        jTxtCorrelativo = new javax.swing.JTextField();
        jLblCodigo1 = new javax.swing.JLabel();
        jTxtProductoID = new javax.swing.JTextField();
        jLblCodigo2 = new javax.swing.JLabel();
        jTxtOfertaID = new javax.swing.JTextField();
        jLblCodigo3 = new javax.swing.JLabel();
        jTxtDescuento = new javax.swing.JTextField();
        jLblCodigo7 = new javax.swing.JLabel();
        jTxtEmpleadoID = new javax.swing.JTextField();
        jLblCodigo6 = new javax.swing.JLabel();
        jTxtFechaIngreso = new javax.swing.JTextField();
        jBtModificarProductoOferta = new javax.swing.JButton();
        jBtnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Modificar Producto Oferta");

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Modificar Producto Oferta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 668, -1));

        jLblCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo.setText("Correlativo:");
        getContentPane().add(jLblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        jTxtCorrelativo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTxtCorrelativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 68, 207, -1));

        jLblCodigo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo1.setText("Producto ID:");
        getContentPane().add(jLblCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jTxtProductoID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTxtProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 114, 207, -1));

        jLblCodigo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo2.setText("Oferta ID:");
        getContentPane().add(jLblCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTxtOfertaID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTxtOfertaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 167, 207, -1));

        jLblCodigo3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo3.setText("Descuento:");
        getContentPane().add(jLblCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jTxtDescuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTxtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 220, 207, -1));

        jLblCodigo7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo7.setText("Empleado ID:");
        getContentPane().add(jLblCodigo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, -1, -1));

        jTxtEmpleadoID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTxtEmpleadoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 302, 207, -1));

        jLblCodigo6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo6.setText("Fecha Ingreso:");
        getContentPane().add(jLblCodigo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 358, -1, -1));

        jTxtFechaIngreso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTxtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 355, 207, -1));

        jBtModificarProductoOferta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtModificarProductoOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.jpg"))); // NOI18N
        jBtModificarProductoOferta.setText("Modificar");
        getContentPane().add(jBtModificarProductoOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 167, -1, -1));

        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_volver.jpg"))); // NOI18N
        jBtnRegresar.setText("Regresar");
        getContentPane().add(jBtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 260, -1, -1));
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtModificarProductoOferta;
    public javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLblCodigo;
    public javax.swing.JLabel jLblCodigo1;
    public javax.swing.JLabel jLblCodigo2;
    public javax.swing.JLabel jLblCodigo3;
    public javax.swing.JLabel jLblCodigo6;
    public javax.swing.JLabel jLblCodigo7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxtCorrelativo;
    public javax.swing.JTextField jTxtDescuento;
    public javax.swing.JTextField jTxtEmpleadoID;
    public javax.swing.JTextField jTxtFechaIngreso;
    public javax.swing.JTextField jTxtOfertaID;
    public javax.swing.JTextField jTxtProductoID;
    // End of variables declaration//GEN-END:variables
}
