/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Marvin Joel
 */
public class JIntFrmInsertarFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntFrmInsertarFactura
     */
    public JIntFrmInsertarFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblCodigo = new javax.swing.JLabel();
        jTxtCorrelativoFactura = new javax.swing.JTextField();
        jLblCodigo1 = new javax.swing.JLabel();
        jTxtNoFactura = new javax.swing.JTextField();
        jLblCodigo2 = new javax.swing.JLabel();
        jTxtSerie = new javax.swing.JTextField();
        jLblCodigo3 = new javax.swing.JLabel();
        jTxtFecha = new javax.swing.JTextField();
        jBtnInsertarFactura = new javax.swing.JButton();
        jBtnRegresar = new javax.swing.JButton();
        jTxtSubtotal = new javax.swing.JTextField();
        jLblCodigo4 = new javax.swing.JLabel();
        jLblCodigo5 = new javax.swing.JLabel();
        jTxtDireccion = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jLblCodigo6 = new javax.swing.JLabel();
        jLblCodigo7 = new javax.swing.JLabel();
        jTxtNit = new javax.swing.JTextField();
        jTxtClienteID = new javax.swing.JTextField();
        jLblCodigo8 = new javax.swing.JLabel();
        jLblCodigo9 = new javax.swing.JLabel();
        jTxtDescuento = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Insertar Factura");

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Insertar Factura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLblCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo.setText("Correlativo Factura:");

        jTxtCorrelativoFactura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLblCodigo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo1.setText("No. Factura:");

        jTxtNoFactura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLblCodigo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo2.setText("serie:");

        jTxtSerie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLblCodigo3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo3.setText("Fecha:");

        jTxtFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jBtnInsertarFactura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnInsertarFactura.setText("Insertar");

        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_volver.jpg"))); // NOI18N
        jBtnRegresar.setText("Regresar");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jTxtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLblCodigo4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo4.setText("Subtotal:");

        jLblCodigo5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo5.setText("Direccion:");

        jTxtDireccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTxtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLblCodigo6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo6.setText("Nombre:");

        jLblCodigo7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo7.setText("Nit:");

        jTxtNit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTxtClienteID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLblCodigo8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo8.setText("Cliente ID:");

        jLblCodigo9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblCodigo9.setText("Descuento:");

        jTxtDescuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCodigo1)
                                    .addComponent(jLblCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtCorrelativoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(jTxtNoFactura)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCodigo3)
                                    .addComponent(jLblCodigo2))
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtFecha)
                                            .addComponent(jTxtSerie)
                                            .addComponent(jTxtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtnInsertarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtnRegresar)))
                                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLblCodigo8)
                            .addComponent(jLblCodigo9)
                            .addComponent(jLblCodigo6)
                            .addComponent(jLblCodigo7)
                            .addComponent(jLblCodigo4)
                            .addComponent(jLblCodigo5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jTxtCorrelativoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo1)
                    .addComponent(jTxtNoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblCodigo2)
                            .addComponent(jTxtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblCodigo3)
                            .addComponent(jTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jBtnInsertarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblCodigo7)
                            .addComponent(jTxtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBtnRegresar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo6)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo5)
                    .addComponent(jTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo4)
                    .addComponent(jTxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo9)
                    .addComponent(jTxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo8)
                    .addComponent(jTxtClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnInsertarFactura;
    public javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLblCodigo;
    public javax.swing.JLabel jLblCodigo1;
    public javax.swing.JLabel jLblCodigo2;
    public javax.swing.JLabel jLblCodigo3;
    public javax.swing.JLabel jLblCodigo4;
    public javax.swing.JLabel jLblCodigo5;
    public javax.swing.JLabel jLblCodigo6;
    public javax.swing.JLabel jLblCodigo7;
    public javax.swing.JLabel jLblCodigo8;
    public javax.swing.JLabel jLblCodigo9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxtClienteID;
    public javax.swing.JTextField jTxtCorrelativoFactura;
    public javax.swing.JTextField jTxtDescuento;
    public javax.swing.JTextField jTxtDireccion;
    public javax.swing.JTextField jTxtFecha;
    public javax.swing.JTextField jTxtNit;
    public javax.swing.JTextField jTxtNoFactura;
    public javax.swing.JTextField jTxtNombre;
    public javax.swing.JTextField jTxtSerie;
    public javax.swing.JTextField jTxtSubtotal;
    // End of variables declaration//GEN-END:variables
}
