/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Marvin Joel
 */
public class JIntlFrmModificarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntlFrmModificarCliente
     */
    public JIntlFrmModificarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnModificarCliente = new javax.swing.JButton();
        jTxtCorreo = new javax.swing.JTextField();
        jLblCodigo5 = new javax.swing.JLabel();
        jLblCodigo4 = new javax.swing.JLabel();
        jTxtDireccion = new javax.swing.JTextField();
        jLblCodigo3 = new javax.swing.JLabel();
        jTxtTelefono = new javax.swing.JTextField();
        jLblCodigo2 = new javax.swing.JLabel();
        jTxtApelldio = new javax.swing.JTextField();
        jLblCodigo1 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLblCodigo = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnRegresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnModificarCliente.setBackground(new java.awt.Color(102, 204, 255));
        jBtnModificarCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.jpg"))); // NOI18N
        jBtnModificarCliente.setText("Modificar");
        jBtnModificarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jBtnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 448, 189, 42));

        jTxtCorreo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 358, 477, -1));

        jLblCodigo5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLblCodigo5.setText("Correo:");
        getContentPane().add(jLblCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, -1, -1));

        jLblCodigo4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLblCodigo4.setText("Dirección:");
        getContentPane().add(jLblCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jTxtDireccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 305, 477, -1));

        jLblCodigo3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLblCodigo3.setText("Telefono:");
        getContentPane().add(jLblCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 257, -1, -1));

        jTxtTelefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 252, 207, -1));

        jLblCodigo2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLblCodigo2.setText("Apellido:");
        getContentPane().add(jLblCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        jTxtApelldio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtApelldio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtApelldio, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 206, 362, -1));

        jLblCodigo1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLblCodigo1.setText("Nombre:");
        getContentPane().add(jLblCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jTxtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 153, 369, -1));

        jLblCodigo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLblCodigo.setText("Código:");
        getContentPane().add(jLblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        jTxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTxtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 107, 207, -1));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Modificar Cliente");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modif.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoP.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(32, 32, 32)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jBtnRegresar.setBackground(new java.awt.Color(51, 204, 255));
        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_volver.jpg"))); // NOI18N
        jBtnRegresar.setText("Regresar ");
        jBtnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 448, 201, 42));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.jpg"))); // NOI18N
        fondo.setText("jLabel4");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    public javax.swing.JButton jBtnModificarCliente;
    public javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLblCodigo;
    public javax.swing.JLabel jLblCodigo1;
    public javax.swing.JLabel jLblCodigo2;
    public javax.swing.JLabel jLblCodigo3;
    public javax.swing.JLabel jLblCodigo4;
    public javax.swing.JLabel jLblCodigo5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxtApelldio;
    public javax.swing.JTextField jTxtCodigo;
    public javax.swing.JTextField jTxtCorreo;
    public javax.swing.JTextField jTxtDireccion;
    public javax.swing.JTextField jTxtNombre;
    public javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables
}
