package vista;
import controlador.ClienteControlador;
import controlador.OfertaControlador;
import controlador.ProductoControlador;
public class MdiEncargadoDeVentas extends javax.swing.JFrame {

    /**
     * Creates new form MdiEncargadoDeVentas
     */
    public MdiEncargadoDeVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeskPEncargadoVentas = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIngresarCliente = new javax.swing.JMenuItem();
        jMenuModificarCliente = new javax.swing.JMenuItem();
        jMenuEliminarCliente = new javax.swing.JMenuItem();
        jMenuListadoClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuIngresarProducto = new javax.swing.JMenuItem();
        jMenuModificarProducto = new javax.swing.JMenuItem();
        jMenuEliminarProducto = new javax.swing.JMenuItem();
        jMenuInventarioProductos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuIngresarOferta = new javax.swing.JMenuItem();
        jMenuModificarOferta = new javax.swing.JMenuItem();
        jMenuEliminarOferta = new javax.swing.JMenuItem();
        jMenuListadoOferta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDeskPEncargadoVentas.setBackground(new java.awt.Color(240, 240, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDeskPEncargadoVentas.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskPEncargadoVentasLayout = new javax.swing.GroupLayout(jDeskPEncargadoVentas);
        jDeskPEncargadoVentas.setLayout(jDeskPEncargadoVentasLayout);
        jDeskPEncargadoVentasLayout.setHorizontalGroup(
            jDeskPEncargadoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskPEncargadoVentasLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 894, Short.MAX_VALUE))
        );
        jDeskPEncargadoVentasLayout.setVerticalGroup(
            jDeskPEncargadoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskPEncargadoVentasLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 487, Short.MAX_VALUE))
        );

        getContentPane().add(jDeskPEncargadoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Clientes");

        jMenuIngresarCliente.setText("Ingresar Cliente");
        jMenuIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIngresarCliente);

        jMenuModificarCliente.setText("Modificar Cliente");
        jMenuModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuModificarCliente);

        jMenuEliminarCliente.setText("Eliminar Cliente");
        jMenuEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEliminarCliente);

        jMenuListadoClientes.setText("Ver Lista Clientes");
        jMenuListadoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuListadoClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuIngresarProducto.setText("Ingresar Producto");
        jMenuIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIngresarProducto);

        jMenuModificarProducto.setText("Modificar Producto");
        jMenuModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuModificarProducto);

        jMenuEliminarProducto.setText("Eliminar Producto");
        jMenuEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuEliminarProducto);

        jMenuInventarioProductos.setText("Ver Inventario Productos");
        jMenuInventarioProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInventarioProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuInventarioProductos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ofertas");

        jMenuIngresarOferta.setText("Insertar Ofertas");
        jMenu3.add(jMenuIngresarOferta);

        jMenuModificarOferta.setText("Modificar Ofertas");
        jMenu3.add(jMenuModificarOferta);

        jMenuEliminarOferta.setText("Eliminar Ofertas");
        jMenu3.add(jMenuEliminarOferta);

        jMenuListadoOferta.setText("Ver Lista de Ofertas");
        jMenu3.add(jMenuListadoOferta);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Factura");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarClienteActionPerformed
        // TODO add your handling code here:
        JIntlFrmModificarCliente modificarCliente = new JIntlFrmModificarCliente();
        ClienteControlador clienteModificar = new ClienteControlador(modificarCliente);
        jDeskPEncargadoVentas.add(modificarCliente);
        modificarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuModificarClienteActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmInsertarProducto insertarProducto = new JIntFrmInsertarProducto();
        ProductoControlador productoIngresar = new ProductoControlador(insertarProducto);
        jDeskPEncargadoVentas.add(insertarProducto);
        insertarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarProductoActionPerformed

    private void jMenuIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarClienteActionPerformed
        // TODO add your handling code here:
        JIntlFrmInsertarCliente insertarCliente = new JIntlFrmInsertarCliente();
        ClienteControlador clienteIngresar = new ClienteControlador(insertarCliente);
        jDeskPEncargadoVentas.add(insertarCliente);
        insertarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarClienteActionPerformed

    private void jMenuEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarClienteActionPerformed
        // TODO add your handling code here:
        JIntlFrmEliminarCliente eliminarCliente = new JIntlFrmEliminarCliente();
        ClienteControlador clienteEliminar = new ClienteControlador(eliminarCliente);
        jDeskPEncargadoVentas.add(eliminarCliente);
        eliminarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarClienteActionPerformed

    private void jMenuListadoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoClientesActionPerformed
        // TODO add your handling code here:
        JIntlFrmListadoClientes listadoCliente = new JIntlFrmListadoClientes();
        ClienteControlador clienteListado = new ClienteControlador(listadoCliente);
        jDeskPEncargadoVentas.add(listadoCliente);
        listadoCliente.setVisible(true);
    }//GEN-LAST:event_jMenuListadoClientesActionPerformed

    private void jMenuModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmModificarProducto modificarProducto = new JIntFrmModificarProducto();
        ProductoControlador productoModificado = new ProductoControlador(modificarProducto);
        jDeskPEncargadoVentas.add(modificarProducto);
        modificarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuModificarProductoActionPerformed

    private void jMenuEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarProductoActionPerformed
        // TODO add your handling code here:
        JIntlFrmEliminarProducto eliminarProducto = new JIntlFrmEliminarProducto();
        ProductoControlador productoEliminar = new ProductoControlador(eliminarProducto);
        jDeskPEncargadoVentas.add(eliminarProducto);
        eliminarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarProductoActionPerformed

    private void jMenuInventarioProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInventarioProductosActionPerformed
        // TODO add your handling code here:
        JIntFrmListadoProducto listadoProducto = new JIntFrmListadoProducto();
        ProductoControlador productoListado = new ProductoControlador(listadoProducto);
        jDeskPEncargadoVentas.add(listadoProducto);
        listadoProducto.setVisible(true);
    }//GEN-LAST:event_jMenuInventarioProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiEncargadoDeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDeskPEncargadoVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEliminarCliente;
    private javax.swing.JMenuItem jMenuEliminarOferta;
    private javax.swing.JMenuItem jMenuEliminarProducto;
    private javax.swing.JMenuItem jMenuIngresarCliente;
    private javax.swing.JMenuItem jMenuIngresarOferta;
    private javax.swing.JMenuItem jMenuIngresarProducto;
    private javax.swing.JMenuItem jMenuInventarioProductos;
    private javax.swing.JMenuItem jMenuListadoClientes;
    private javax.swing.JMenuItem jMenuListadoOferta;
    private javax.swing.JMenuItem jMenuModificarCliente;
    private javax.swing.JMenuItem jMenuModificarOferta;
    private javax.swing.JMenuItem jMenuModificarProducto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
