package vista;
import controlador.ClienteControlador;
import controlador.OfertaControlador;
import controlador.ProductoControlador;
import controlador.DetalleFacturaControlador;
import controlador.FacturaControlador;
import controlador.EmpleadoControlador;
import controlador.ProductoOfertaControlador;
import controlador.PuestosControlador;
import controlador.TipoProductoControlador;
public class MdiEncargadoDeVentas extends javax.swing.JFrame {

    /**
     * Creates new form MdiEncargadoDeVentas
     */
    public MdiEncargadoDeVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeskPEncargadoVentas = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIngresarCliente = new javax.swing.JMenuItem();
        jMenuModificarCliente = new javax.swing.JMenuItem();
        jMenuEliminarCliente = new javax.swing.JMenuItem();
        jMenuListadoClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuIngresarProducto = new javax.swing.JMenuItem();
        jMenuModificarProducto = new javax.swing.JMenuItem();
        jMenuEliminarProducto = new javax.swing.JMenuItem();
        jMenuInventarioProductos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuIngresarOferta = new javax.swing.JMenuItem();
        jMenuModificarOferta = new javax.swing.JMenuItem();
        jMenuEliminarOferta = new javax.swing.JMenuItem();
        jMenuListadoOferta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuListadoFactura = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuInsertarProductoOferta = new javax.swing.JMenuItem();
        jMenuModificarProductoOferta = new javax.swing.JMenuItem();
        jMenuEliminarProductoOferta = new javax.swing.JMenuItem();
        jMenuListadoProductoOferta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuInsertarTipoProducto = new javax.swing.JMenuItem();
        jMenuModificarTipoProducto = new javax.swing.JMenuItem();
        jMenuEliminarTipoProducto = new javax.swing.JMenuItem();
        jMenuListadoTipoProducto = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuListadoDetalleFactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDeskPEncargadoVentas.setBackground(new java.awt.Color(240, 240, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1968, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDeskPEncargadoVentas.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskPEncargadoVentasLayout = new javax.swing.GroupLayout(jDeskPEncargadoVentas);
        jDeskPEncargadoVentas.setLayout(jDeskPEncargadoVentasLayout);
        jDeskPEncargadoVentasLayout.setHorizontalGroup(
            jDeskPEncargadoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskPEncargadoVentasLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 894, Short.MAX_VALUE))
        );
        jDeskPEncargadoVentasLayout.setVerticalGroup(
            jDeskPEncargadoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskPEncargadoVentasLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 487, Short.MAX_VALUE))
        );

        getContentPane().add(jDeskPEncargadoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Clientes");

        jMenuIngresarCliente.setText("Ingresar Cliente");
        jMenuIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIngresarCliente);

        jMenuModificarCliente.setText("Modificar Cliente");
        jMenuModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuModificarCliente);

        jMenuEliminarCliente.setText("Eliminar Cliente");
        jMenuEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEliminarCliente);

        jMenuListadoClientes.setText("Ver Lista Clientes");
        jMenuListadoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuListadoClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuIngresarProducto.setText("Ingresar Producto");
        jMenuIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIngresarProducto);

        jMenuModificarProducto.setText("Modificar Producto");
        jMenuModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuModificarProducto);

        jMenuEliminarProducto.setText("Eliminar Producto");
        jMenuEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuEliminarProducto);

        jMenuInventarioProductos.setText("Ver Inventario Productos");
        jMenuInventarioProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInventarioProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuInventarioProductos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ofertas");

        jMenuIngresarOferta.setText("Insertar Ofertas");
        jMenuIngresarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarOfertaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuIngresarOferta);

        jMenuModificarOferta.setText("Modificar Ofertas");
        jMenuModificarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarOfertaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuModificarOferta);

        jMenuEliminarOferta.setText("Eliminar Ofertas");
        jMenuEliminarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarOfertaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEliminarOferta);

        jMenuListadoOferta.setText("Ver Lista de Ofertas");
        jMenuListadoOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoOfertaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuListadoOferta);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Factura");

        jMenuListadoFactura.setText("Listado de Factura");
        jMenuListadoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoFacturaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuListadoFactura);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Producto Oferta");

        jMenuInsertarProductoOferta.setText("Insertar Producto Oferta");
        jMenuInsertarProductoOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInsertarProductoOfertaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuInsertarProductoOferta);

        jMenuModificarProductoOferta.setText("Modificar Producto Oferta");
        jMenuModificarProductoOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarProductoOfertaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuModificarProductoOferta);

        jMenuEliminarProductoOferta.setText("Eliminar Producto Oferta");
        jMenuEliminarProductoOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarProductoOfertaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuEliminarProductoOferta);

        jMenuListadoProductoOferta.setText("Listado Producto Oferta");
        jMenuListadoProductoOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoProductoOfertaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuListadoProductoOferta);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Tipos Productos");

        jMenuInsertarTipoProducto.setText("Insertar Tipo Producto");
        jMenuInsertarTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInsertarTipoProductoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuInsertarTipoProducto);

        jMenuModificarTipoProducto.setText("Modificar Tipo Producto");
        jMenuModificarTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarTipoProductoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuModificarTipoProducto);

        jMenuEliminarTipoProducto.setText("Eliminar Tipo Producto");
        jMenuEliminarTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarTipoProductoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuEliminarTipoProducto);

        jMenuListadoTipoProducto.setText("Listado Tipo Producto");
        jMenuListadoTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoTipoProductoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuListadoTipoProducto);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Detalle Factura");

        jMenuListadoDetalleFactura.setText("Listado Detalle Factura");
        jMenuListadoDetalleFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListadoDetalleFacturaActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuListadoDetalleFactura);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarClienteActionPerformed
        // TODO add your handling code here:
        JIntlFrmModificarCliente modificarCliente = new JIntlFrmModificarCliente();
        ClienteControlador clienteModificar = new ClienteControlador(modificarCliente);
        jDeskPEncargadoVentas.add(modificarCliente);
        modificarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuModificarClienteActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmInsertarProducto insertarProducto = new JIntFrmInsertarProducto();
        ProductoControlador productoIngresar = new ProductoControlador(insertarProducto);
        jDeskPEncargadoVentas.add(insertarProducto);
        insertarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarProductoActionPerformed

    private void jMenuIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarClienteActionPerformed
        // TODO add your handling code here:
        JIntlFrmInsertarCliente insertarCliente = new JIntlFrmInsertarCliente();
        ClienteControlador clienteIngresar = new ClienteControlador(insertarCliente);
        jDeskPEncargadoVentas.add(insertarCliente);
        insertarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarClienteActionPerformed

    private void jMenuEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarClienteActionPerformed
        // TODO add your handling code here:
        JIntlFrmEliminarCliente eliminarCliente = new JIntlFrmEliminarCliente();
        ClienteControlador clienteEliminar = new ClienteControlador(eliminarCliente);
        jDeskPEncargadoVentas.add(eliminarCliente);
        eliminarCliente.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarClienteActionPerformed

    private void jMenuListadoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoClientesActionPerformed
        // TODO add your handling code here:
        JIntlFrmListadoClientes listadoCliente = new JIntlFrmListadoClientes();
        ClienteControlador clienteListado = new ClienteControlador(listadoCliente);
        jDeskPEncargadoVentas.add(listadoCliente);
        listadoCliente.setVisible(true);
    }//GEN-LAST:event_jMenuListadoClientesActionPerformed

    private void jMenuModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmModificarProducto modificarProducto = new JIntFrmModificarProducto();
        ProductoControlador productoModificado = new ProductoControlador(modificarProducto);
        jDeskPEncargadoVentas.add(modificarProducto);
        modificarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuModificarProductoActionPerformed

    private void jMenuEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarProductoActionPerformed
        // TODO add your handling code here:
        JIntlFrmEliminarProducto eliminarProducto = new JIntlFrmEliminarProducto();
        ProductoControlador productoEliminar = new ProductoControlador(eliminarProducto);
        jDeskPEncargadoVentas.add(eliminarProducto);
        eliminarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarProductoActionPerformed

    private void jMenuInventarioProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInventarioProductosActionPerformed
        // TODO add your handling code here:
        JIntFrmListadoProducto listadoProducto = new JIntFrmListadoProducto();
        ProductoControlador productoListado = new ProductoControlador(listadoProducto);
        jDeskPEncargadoVentas.add(listadoProducto);
        listadoProducto.setVisible(true);
    }//GEN-LAST:event_jMenuInventarioProductosActionPerformed

    private void jMenuIngresarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmInsertarOferta insertarOferta = new JIntFrmInsertarOferta();
        OfertaControlador ofertaControlador = new OfertaControlador(insertarOferta);
        jDeskPEncargadoVentas.add(insertarOferta);
        insertarOferta.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarOfertaActionPerformed

    private void jMenuModificarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmModificarOferta modificarOferta = new JIntFrmModificarOferta();
        OfertaControlador ofertaControlador = new OfertaControlador(modificarOferta);
        jDeskPEncargadoVentas.add(modificarOferta);
        modificarOferta.setVisible(true);
    }//GEN-LAST:event_jMenuModificarOfertaActionPerformed

    private void jMenuEliminarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmEliminarOferta eliminarOferta = new JIntFrmEliminarOferta();
        OfertaControlador ofertaControlador = new OfertaControlador(eliminarOferta);
        jDeskPEncargadoVentas.add(eliminarOferta);
        eliminarOferta.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarOfertaActionPerformed

    private void jMenuListadoOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmListadoOfertas listadoOferta = new JIntFrmListadoOfertas();
        OfertaControlador ofertaControlador = new OfertaControlador(listadoOferta);
        jDeskPEncargadoVentas.add(listadoOferta);
        listadoOferta.setVisible(true);
    }//GEN-LAST:event_jMenuListadoOfertaActionPerformed

    private void jMenuListadoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoFacturaActionPerformed
        // TODO add your handling code here:
        JIntFrmListadoFactura listadoFactura = new JIntFrmListadoFactura();
        FacturaControlador facturaControlador = new FacturaControlador(listadoFactura);
        jDeskPEncargadoVentas.add(listadoFactura);
        listadoFactura.setVisible(true);
    }//GEN-LAST:event_jMenuListadoFacturaActionPerformed

    private void jMenuInsertarProductoOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInsertarProductoOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmInsertarProductoOferta insertarProductoO = new JIntFrmInsertarProductoOferta();
        ProductoOfertaControlador productoOControlador = new ProductoOfertaControlador(insertarProductoO);
        jDeskPEncargadoVentas.add(insertarProductoO);
        insertarProductoO.setVisible(true);
    }//GEN-LAST:event_jMenuInsertarProductoOfertaActionPerformed

    private void jMenuModificarProductoOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarProductoOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmModificarProductoOferta modificarProductoO = new JIntFrmModificarProductoOferta();
        ProductoOfertaControlador productoOControlador = new ProductoOfertaControlador(modificarProductoO);
        jDeskPEncargadoVentas.add(modificarProductoO);
        modificarProductoO.setVisible(true);
    }//GEN-LAST:event_jMenuModificarProductoOfertaActionPerformed

    private void jMenuEliminarProductoOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarProductoOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmEliminarProductoOferta eliminarProductoO = new JIntFrmEliminarProductoOferta();
        ProductoOfertaControlador productoOControlador = new ProductoOfertaControlador(eliminarProductoO);
        jDeskPEncargadoVentas.add(eliminarProductoO);
        eliminarProductoO.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarProductoOfertaActionPerformed

    private void jMenuListadoProductoOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoProductoOfertaActionPerformed
        // TODO add your handling code here:
        JIntFrmListadoProductoOferta listadoProductoO = new JIntFrmListadoProductoOferta();
        ProductoOfertaControlador productoOControlador = new ProductoOfertaControlador(listadoProductoO);
        jDeskPEncargadoVentas.add(listadoProductoO);
        listadoProductoO.setVisible(true);
    }//GEN-LAST:event_jMenuListadoProductoOfertaActionPerformed

    private void jMenuInsertarTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInsertarTipoProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmInsertarTipoProducto insertarTipo = new JIntFrmInsertarTipoProducto();
        TipoProductoControlador tipoOControlador = new TipoProductoControlador(insertarTipo);
        jDeskPEncargadoVentas.add(insertarTipo);
        insertarTipo.setVisible(true);
    }//GEN-LAST:event_jMenuInsertarTipoProductoActionPerformed

    private void jMenuModificarTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarTipoProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmModificarTipoProducto modificarTipo = new JIntFrmModificarTipoProducto();
        TipoProductoControlador tipoOControlador = new TipoProductoControlador(modificarTipo);
        jDeskPEncargadoVentas.add(modificarTipo);
        modificarTipo.setVisible(true);
    }//GEN-LAST:event_jMenuModificarTipoProductoActionPerformed

    private void jMenuEliminarTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarTipoProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmEliminarTipoProducto eliminarTipo = new JIntFrmEliminarTipoProducto();
        TipoProductoControlador tipoOControlador = new TipoProductoControlador(eliminarTipo);
        jDeskPEncargadoVentas.add(eliminarTipo);
        eliminarTipo.setVisible(true);
    }//GEN-LAST:event_jMenuEliminarTipoProductoActionPerformed

    private void jMenuListadoTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoTipoProductoActionPerformed
        // TODO add your handling code here:
        JIntFrmListadoTipoProducto listadoTipo = new JIntFrmListadoTipoProducto();
        TipoProductoControlador tipoOControlador = new TipoProductoControlador(listadoTipo);
        jDeskPEncargadoVentas.add(listadoTipo);
        listadoTipo.setVisible(true);
    }//GEN-LAST:event_jMenuListadoTipoProductoActionPerformed

    private void jMenuListadoDetalleFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoDetalleFacturaActionPerformed
        // TODO add your handling code here:
        JIntlFrmListadoDetalleFactura listadoDetalle = new JIntlFrmListadoDetalleFactura();
        DetalleFacturaControlador tipoOControlador = new DetalleFacturaControlador(listadoDetalle);
        jDeskPEncargadoVentas.add(listadoDetalle);
        listadoDetalle.setVisible(true);
    }//GEN-LAST:event_jMenuListadoDetalleFacturaActionPerformed

    /** a las 5:34 si funcionava despues no
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiEncargadoDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiEncargadoDeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDeskPEncargadoVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEliminarCliente;
    private javax.swing.JMenuItem jMenuEliminarOferta;
    private javax.swing.JMenuItem jMenuEliminarProducto;
    private javax.swing.JMenuItem jMenuEliminarProductoOferta;
    private javax.swing.JMenuItem jMenuEliminarTipoProducto;
    private javax.swing.JMenuItem jMenuIngresarCliente;
    private javax.swing.JMenuItem jMenuIngresarOferta;
    private javax.swing.JMenuItem jMenuIngresarProducto;
    private javax.swing.JMenuItem jMenuInsertarProductoOferta;
    private javax.swing.JMenuItem jMenuInsertarTipoProducto;
    private javax.swing.JMenuItem jMenuInventarioProductos;
    private javax.swing.JMenuItem jMenuListadoClientes;
    private javax.swing.JMenuItem jMenuListadoDetalleFactura;
    private javax.swing.JMenuItem jMenuListadoFactura;
    private javax.swing.JMenuItem jMenuListadoOferta;
    private javax.swing.JMenuItem jMenuListadoProductoOferta;
    private javax.swing.JMenuItem jMenuListadoTipoProducto;
    private javax.swing.JMenuItem jMenuModificarCliente;
    private javax.swing.JMenuItem jMenuModificarOferta;
    private javax.swing.JMenuItem jMenuModificarProducto;
    private javax.swing.JMenuItem jMenuModificarProductoOferta;
    private javax.swing.JMenuItem jMenuModificarTipoProducto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
